---
# system_packages for Workstation Personalization
packages_system_packages:
  Debian:
    core:
      - { pkg: "zsh", bin: "zsh" }
      - { pkg: "stow", bin: "stow" }
      - { pkg: "git", bin: "git" }
      - { pkg: "curl", bin: "curl" }
      - { pkg: "wget", bin: "wget" }
      - { pkg: "inotify-tools", bin: "inotifywait" } # dependency for process-inbox
    utilities:
      - { pkg: "htop", bin: "htop" }
      - { pkg: "sysstat", bin: "sar" }
      - { pkg: "traceroute", bin: "traceroute" }
      - { pkg: "iproute2", bin: "ip" }
      - { pkg: "pipx", bin: "pipx" }
    optional:
      - { pkg: "btop", bin: "btop" }
      - { pkg: "neofetch", bin: "neofetch" }
      - { pkg: "tmux", bin: "tmux" }
      - { pkg: "tree", bin: "tree" }
      - { pkg: "kate", bin: "kate" }
      - { pkg: "doublecmd-qt", bin: "doublecmd" }
      - { pkg: "pavucontrol", bin: "pavucontrol" }

  RedHat:
    core:
      - { pkg: "zsh", bin: "zsh" }
      - { pkg: "stow", bin: "stow" }
      - { pkg: "git", bin: "git" }
      - { pkg: "curl", bin: "curl" }
      - { pkg: "wget", bin: "wget" }
      - { pkg: "util-linux-user", bin: "chsh" }
      - { pkg: "inotify-tools", bin: "inotifywait" } # dependency for process-inbox
    utilities:
      - { pkg: "htop", bin: "htop" }
      - { pkg: "sysstat", bin: "sar" }
      - { pkg: "traceroute", bin: "traceroute" }
      - { pkg: "iproute", bin: "ip" }
      - { pkg: "pipx", bin: "pipx" }
    optional:
      - { pkg: "btop", bin: "btop" }
      - { pkg: "fastfetch", bin: "fastfetch" }
      - { pkg: "tmux", bin: "tmux" }
      - { pkg: "tree", bin: "tree" }
      - { pkg: "kate", bin: "kate" }
      - { pkg: "doublecmd-qt", bin: "doublecmd" }
      - { pkg: "pavucontrol", bin: "pavucontrol" }

packages_flatpak_packages:
  - com.google.Chrome
  - md.obsidian.Obsidian
  - org.audacityteam.Audacity
  - org.videolan.VLC
  - org.ferdium.Ferdium
  - com.freerdp.FreeRDP
  - com.obsproject.Studio
  - com.microsoft.Edge
  - org.mozilla.Thunderbird
  - org.remmina.Remmina
