- name: Install system dependencies for OCI SDK (RedHat)
  ansible.builtin.package:
    name: [python3-pip, python3-setuptools, openssl, gcc, libffi-devel]
    state: present
  when: ansible_facts['os_family'] == "RedHat"
  become: true

- name: Install system dependencies for OCI SDK (Debian)
  ansible.builtin.package:
    name: [python3-pip, python3-setuptools, python3-venv, build-essential, libffi-dev]
    state: present
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Create OCI venv and install OCI packages
  ansible.builtin.pip:
    name: [pip, oci, oci-cli]
    state: present
    virtualenv: "{{ oci_venv_path }}"
    virtualenv_command: python3 -m venv
  become: true

- name: Create OCI configuration directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.oci"
    state: directory
    mode: '0700'

- name: Deploy OCI configuration file
  ansible.builtin.template:
    src: oci_config.j2
    dest: "{{ ansible_facts['user_dir'] }}/.oci/config"
    mode: '0600'

- name: OCI - Deploy Private Key
  ansible.builtin.copy:
    content: "{{ private_key }}"
    dest: "{{ ansible_facts['user_dir'] }}/.oci/oci_api_key.pem"
    mode: '0600'
  no_log: true  # Hide sensitive data from logs

- name: Check if OCI API key exists
  ansible.builtin.stat:
    path: "{{ ansible_facts['user_dir'] }}/.oci/oci_api_key.pem"
  register: management_oci_key_stat

- name: Generate OCI API private key if missing
  ansible.builtin.command: >
    openssl genrsa -out {{ ansible_facts['user_dir'] }}/.oci/oci_api_key.pem 2048
  args:
    creates: "{{ ansible_facts['user_dir'] }}/.oci/oci_api_key.pem"
  when: not management_oci_key_stat.stat.exists

- name: Generate OCI API public key
  ansible.builtin.command: >
    openssl rsa -pubout -in {{ ansible_facts['user_dir'] }}/.oci/oci_api_key.pem
    -out {{ ansible_facts['user_dir'] }}/.oci/oci_api_key_public.pem
  args:
    creates: "{{ ansible_facts['user_dir'] }}/.oci/oci_api_key_public.pem"

- name: Fetch public key for manual console upload
  ansible.builtin.slurp:
    src: "{{ ansible_facts['user_dir'] }}/.oci/oci_api_key_public.pem"
  register: management_oci_pub_key

- name: Show Public Key for OCI Console
  ansible.builtin.debug:
    msg: "{{ management_oci_pub_key['content'] | b64decode }}"
