---
- name: Linux - SSH hardening (core settings)
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    validate: 'sshd -t -f %s'
    backup: true
  loop:
    - { regexp: '^#?Port', line: "Port {{ hardening_ssh_port }}" }
    - { regexp: '^#?PermitRootLogin', line: "PermitRootLogin {{ hardening_permit_root_login }}" }
    - { regexp: '^#?PasswordAuthentication', line: "PasswordAuthentication {{ hardening_password_auth }}" }
  notify: restart ssh
  when: not (hardening_verify_only | default(false))
  tags:
    - security
    - security:auth
    - security:ssh

