---
- name: Linux - allow SSH in firewalld
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    state: enabled
    immediate: true
  when: ansible_facts['os_family'] == "RedHat"
  notify: reload firewalld

- name: Linux - allow SSH in UFW
  community.general.ufw:
    rule: allow
    name: OpenSSH
    state: enabled
  when: ansible_facts['os_family'] == "Debian"
  notify: reload ufw

