---
- name: Apply Infrastructure State
  hosts: all
  become: true
  roles:
    - { role: bootstrap, tags: ['bootstrap', 'setup'] }
    - { role: common,    tags: ['common', 'packages'] }
    - { role: tailscale, tags: ['tailscale', 'network'] }
    - { role: security_hardening, tags: ['security'] }
