---
# tasks file for /home/bhupi/ansible/roles/packages
- name: Install Core and Utility packages
  ansible.builtin.package:
    name: "{{ item.pkg }}"
    state: present
  loop: "{{ packages_system_packages[ansible_facts['os_family']].core + packages_system_packages[ansible_facts['os_family']].utilities }}"
  become: true
  tags: [core]

- name: Install Optional quality-of-life packages
  ansible.builtin.package:
    name: "{{ item.pkg }}"
    state: present
  loop: "{{ packages_system_packages[ansible_facts['os_family']].optional }}"
  become: true
  tags: [optional]

- name: Ensure Flatpak is installed
  ansible.builtin.package:
    name: flatpak
    state: present
  become: true
  tags: [flatpak, gui]

- name: Install Fedora KDE Group (if missing)
  ansible.builtin.dnf:
    name: "@kde-desktop-environment"
    state: present
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_distribution == 'Fedora'
  become: true
  tags: [gui, kde]

- name: Ensure Flathub repository is enabled
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true
  tags: [flatpak, gui]

- name: Install GUI Apps via Flatpak
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
    remote: flathub
  loop: "{{ packages_flatpak_packages }}"
  become: true
  tags: [flatpak, gui]
