---
# tasks file for /home/bhupi/ansible/roles/packages
- name: Install Core and Utility packages
  ansible.builtin.package:
    name: "{{ item.pkg }}"
    state: present
  loop: "{{ system_packages[ansible_facts['os_family']].core + system_packages[ansible_facts['os_family']].utilities }}"
  become: true
  tags: [core]

- name: Install Optional quality-of-life packages
  ansible.builtin.package:
    name: "{{ item.pkg }}"
    state: present
  loop: "{{ system_packages[ansible_facts['os_family']].optional }}"
  become: true
  tags: [optional]

- name: Ensure Flatpak is installed
  ansible.builtin.package:
    name: flatpak
    state: present
  become: true
  tags: [flatpak, gui]

- name: Ensure Flathub repository is enabled
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  become: true
  tags: [flatpak, gui]

- name: Install GUI Apps via Flatpak
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
    remote: flathub
  loop: "{{ flatpak_packages }}"
  become: true
  tags: [flatpak, gui]

- name: Ensure KWallet Secret Service bridge is installed
  dnf:
    name: kwallet-pam
    state: present
  become: true
  tags: [vscode, config]

- name: VS Code | Ensure Flatpak config directory exists
  ansible.builtin.file:
    path: "~/.var/app/com.visualstudio.code/config/Code/User"
    state: directory
    mode: '0755'
    tags: [vscode, config]

- name: VS Code | Force KWallet6 encryption in argv.json
  ansible.builtin.copy:
    dest: "~/.var/app/com.visualstudio.code/config/Code/User/argv.json"
    content: |
      {
          "password-store": "kwallet6"
      }
    mode: '0644'
  tags: [vscode, config]

- name: VS Code | Grant Flatpak permissions for KWallet, Terminal, and Podman
  ansible.builtin.command:
    cmd: >
      flatpak override --user
      --talk-name=org.freedesktop.Flatpak
      --talk-name=org.freedesktop.secrets
      --talk-name=org.kde.kwalletd5
      --talk-name=org.kde.kwalletd6
      --filesystem=xdg-run/podman:create
      --filesystem=home
      com.visualstudio.code
  register: vscode_flatpak_override
  changed_when: false
  tags: [vscode, flatpak]
