---
# tasks file for roles/podman
- name: Podman | Ensure Podman and Docker-compatibility are installed
  ansible.builtin.package:
    name:
      - podman
      - podman-docker
    state: present
  become: true

- name: Podman | Enable the User Socket
  ansible.builtin.systemd:
    name: podman.socket
    state: started
    enabled: true
    scope: user

- name: Podman | Enable lingering for the user
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ ansible_facts['user_id'] }}"
    creates: "/var/lib/systemd/linger/{{ ansible_facts['user_id'] }}"
  become: true

- name: Podman | Set DOCKER_HOST for rootless Podman
  ansible.builtin.lineinfile:
    path: "~/.zshrc"
    regexp: "^export DOCKER_HOST="
    line: 'export DOCKER_HOST=unix:///run/user/{{ ansible_facts["user_uid"] }}/podman/podman.sock'
    create: true
    mode: "0700"
  tags: [podman, shell]

- name: Podman | Create Bulletproof Flatpak-friendly wrapper
  ansible.builtin.copy:
    dest: "{{ ansible_facts['user_dir'] }}/.local/bin/podman-host"
    mode: "0755"
    content: |
      #!/bin/bash
      # Match "version" and anything that follows it
      if [[ "$1" == "version" ]]; then
          echo '{"Client": {"Version": "24.0.0"}, "Server": {"Version": "24.0.0"}, "ApiVersion": "1.41"}'
          exit 0
      fi

      if [ -f /.flatpak-info ]; then
          exec flatpak-spawn --host podman "$@"
      else
          exec podman "$@"
      fi
  tags: [podman, shell]

- name: Podman | Create docker symlink for VS Code
  ansible.builtin.file:
    src: "{{ ansible_facts['user_dir'] }}/.local/bin/podman-host"
    dest: "{{ ansible_facts['user_dir'] }}/.local/bin/docker"
    state: link
  tags: [podman, shell]

- name: Podman | Pre-cache the Toolbox image
  ansible.builtin.command:
    cmd: "podman pull {{ podman_toolbox_image }}"
  changed_when: false
