# tasks file for roles/clone_dotfiles
---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.ssh"
    state: directory
    mode: '0700'

- name: Deploy Private SSH Key from Vault
  ansible.builtin.copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ ansible_facts['user_dir'] }}/.ssh/id_ed25519"
    mode: '0600'
    force: false  # Avoid overwriting if the file already exists
  no_log: true  # Hide sensitive data from logs

- name: Sync Dotfiles Repository
  ansible.builtin.git:
    repo: "{{ clone_dotfiles_repo }}"
    dest: "{{ clone_dotfiles_home }}"
    version: "{{ clone_dotfiles_branch }}"
    accept_hostkey: true
    update: true
    force: true
