# tasks file for roles/clone_dotfiles
---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ clone_dotfiles_user_home }}/.ssh"
    state: directory
    mode: "0700"
  become: true
  become_user: "{{ clone_dotfiles_user }}"

- name: Deploy Private SSH Key from Vault
  ansible.builtin.copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ clone_dotfiles_user_home }}/.ssh/id_ed25519"
    mode: "0600"
    force: true
  no_log: true # Hide sensitive data from logs
  become: true
  become_user: "{{ clone_dotfiles_user }}"

- name: Sync Dotfiles Repository
  ansible.builtin.git:
    repo: "{{ clone_dotfiles_repo }}"
    dest: "{{ clone_dotfiles_home }}"
    version: "{{ clone_dotfiles_branch }}"
    accept_hostkey: true
    key_file: "{{ clone_dotfiles_user_home }}/.ssh/id_ed25519"
    ssh_opts: "-o IdentitiesOnly=yes"
    update: true
    force: true
  become: true
  become_user: "{{ clone_dotfiles_user }}"
