- name: Phase 4 - Final Visual Automation
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure Wallpaper Script is executable
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/dotfiles/scripts/wallpaper_wallhaven.sh"
        mode: '0755'

    - name: Set up 3:00 AM Gym Wallpaper Cron
      ansible.builtin.cron:
        name: "Daily Wallhaven Refresh"
        minute: "0"
        hour: "3"
        job: "/bin/bash {{ ansible_facts['user_dir'] }}/dotfiles/scripts/wallpaper_wallhaven.sh"

    - name: Run initial wallpaper fetch
      ansible.builtin.command: "/bin/bash {{ ansible_facts['user_dir'] }}/dotfiles/scripts/wallpaper_wallhaven.sh"
      register: wallpaper_output
      changed_when: "'Wallpaper updated' in wallpaper_output.stdout"
