---
- name: Check Tailscale login status
  ansible.builtin.command: tailscale status
  register: tailscale_status_check
  failed_when: false
  changed_when: false

- name: Connect to Tailscale network
  ansible.builtin.command:
    cmd: "tailscale up --authkey={{ tailscale_auth_key }} --accept-routes --reset"
  # We only run this if we aren't already 'active'
  when:
    - tailscale_auth_key is defined
    - "'Logged in' not in tailscale_status_check.stdout"
  register: tailscale_up_result
  # Use no_log to protect your key, but turn it off if you need to debug!
  no_log: true
  become: true

- name: Run Tailscale up command
  ansible.builtin.command:
    cmd: tailscale up --authkey={{ tailscale_auth_key }}
  register: tailscale_up_result
  changed_when: "'Success.' in tailscale_up_result.stdout"
  failed_when: "tailscale_up_result.rc != 0 or 'Error' in tailscale_up_result.stderr"

- name: Display Tailscale IP address
  ansible.builtin.debug:
    msg: "Tailscale IP: {{ ansible_facts['all_ipv4_addresses'] | select('match', '^100\\.') | first | default('Not Found') }}"
