---
dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: localhost

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    hosts:
      all:
        hosts:
          localhost:
            ansible_connection: local
  playbooks:
    converge: converge.yml
    verify: verify.yml

scenario:
  test_sequence:
    - syntax

verifier:
  name: ansible
