# SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: "Bhupinder Singh Gill"
  description: "Install and configure Gemini CLI"
  company: "Personal"
  license: "MIT"
  min_ansible_version: "2.12"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - ai
    - cli
    - gemini

dependencies: []
