---
# defaults file for roles/clone_dotfiles
clone_dotfiles_repo: "https://github.com/bhupinderhappy777/dotfiles.git"
clone_dotfiles_home: "{{ ansible_user_dir }}/dotfiles"
clone_dotfiles_branch: "main"
